name: Develop manually
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: To test server?
        default: true
        required: true
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project packages
        run: npm install
      - name: Build project to production
        run: npm run build:prod
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ducatus-dist
          path: ./dist
          retention-days: 3
  deploy:
    name: Deploy project to test server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
        with:
          name: ducatus-dist
      - name: ls
        run: ls
      - name: Deploying to server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: ${{ secrets.DEPLOY_TEST_SWITCHES }}
          path: ${{ secrets.DEPLOY_TEST_PATH }}
          remote_path: ${{ secrets.DEPLOY_TEST_REMOTE_PATH }}
          remote_host: ${{ secrets.DEPLOY_TEST_HOST }}
          remote_port: ${{ secrets.DEPLOY_TEST_PORT }}
          remote_user: ${{ secrets.DEPLOY_TEST_USER }}
          remote_key: ${{ secrets.DEPLOY_TEST_KEY }}
